#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

APP_BASE_NAME=`basename "$0"`
APP_HOME=`cd "${0%/*}" > /dev/null; pwd -P`

DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

GRADLE_OPTS=""

if [ ! -f "$CLASSPATH" ]; then
  echo "gradle-wrapper.jar not found. Please run 'gradle wrapper' with a local Gradle installation." >&2
  exit 1
fi

exec "$JAVA_HOME/bin/java" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
